pub mod adminclientes;
pub mod adminconfig;
pub mod adminempleados;
pub mod adminfinanzas;
pub mod admininventory;
pub mod adminparser;
pub mod admintarvis;
pub mod admintickets;
pub mod adminventas;
